# Generated by Django 4.2.4 on 2023-08-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('image', models.ImageField(upload_to='', verbose_name='imagen')),
                ('details', models.CharField(max_length=600, verbose_name='detalle')),
                ('price', models.CharField(max_length=80, verbose_name='precio')),
                ('gender', models.CharField(max_length=80, verbose_name='género')),
                ('stock', models.PositiveIntegerField(verbose_name='stock')),
                ('deleted', models.BooleanField(default=False, verbose_name='eliminado')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
